update sponsorship package
Code-and-Coffee-YVR/sponsorship-package pull request #3
Opened 2016-09-29 13:51 UTC by philweier

A simplified sponsorship package with rates based on duration.

2016-09-29 14:28 UTC, jenncoop commented
This is a bit hard to read:

<img width="810" alt="screen shot 2016-09-29 at 7 25 24 am" src="https://cloud.githubusercontent.com/assets/453549/18958060/3038db8c-8616-11e6-91db-dd52e7f4ff33.png">

I think you meant it to be a list, no?

Otherwise, looks good to me.

2016-09-29 21:53 UTC, whilestevego requested changes
Aside from that one change. It looks great. Thanks for the update!

2016-09-29 21:53 UTC, whilestevego commented on README.md
> +
I agree with @jenncoop that this part should be a list 😃

2016-09-30 14:27 UTC, whilestevego approved these changes

2016-09-30 14:28 UTC, whilestevego commented
![](http://i.imgur.com/FeaesgO.gif)

2016-09-30 14:31 UTC, merged